version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: "prowessive-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    network_mode: host